
#include "MDIO_INTERFACE.h"
#include "HSTEPPER_INTERFACE.h"
#define  F_CPU 16000000UL
#include <util/delay.h>

void HSTEPPER_VidInit(void)
{
	MDIO_ERROR_STATE_t_SetPinDirection(STEPPER_MOTOR_PIN_1, OUTPUT);
	MDIO_ERROR_STATE_t_SetPinDirection(STEPPER_MOTOR_PIN_2, OUTPUT);
	MDIO_ERROR_STATE_t_SetPinDirection(STEPPER_MOTOR_PIN_3, OUTPUT);
	MDIO_ERROR_STATE_t_SetPinDirection(STEPPER_MOTOR_PIN_4, OUTPUT);
}


void HSTEPPER_VidFullStepRight(void)
{
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,HIGH);
	_delay_ms(10);
}


void HSTEPPER_VidFullStepLeft(void)
{
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,HIGH);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
}


void HSTEPPER_VidHalfStepRight(void)
{
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,HIGH);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,HIGH);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,HIGH);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
}


void HSTEPPER_VidHalfStepLeft(void)
{
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,HIGH);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,HIGH);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
	_delay_ms(10);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,HIGH);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,HIGH);
	_delay_ms(10);
}


void HSTEPPER_VidFullStep_FullMechanicalRevolutionRight(void)
{
	u8 i;
	for(i=0 ; i<STEPS_PER_REVOLUTION ; i++)
	{
		HSTEPPER_VidFullStepRight();
	}
}


void HSTEPPER_VidFullStep_FullMechanicalRevolutionLeft(void)
{
	u8 i;
	for(i=0 ; i<STEPS_PER_REVOLUTION ; i++)
	{
		HSTEPPER_VidFullStepLeft();
	}
}


void HSTEPPER_VidHalfStep_FullMechanicalRevolutionRight(void)
{
	u8 i;
	for(i=0 ; i<STEPS_PER_REVOLUTION ; i++)
	{
		HSTEPPER_VidHalfStepRight();
	}
}


void HSTEPPER_VidHalfStep_FullMechanicalRevolutionLeft(void)
{
	u8 i;
	for(i=0 ; i<STEPS_PER_REVOLUTION ; i++)
	{
		HSTEPPER_VidHalfStepLeft();
	}
}


void HSTEPPER_VidFullStep_StartRight(u8 Copy_u8NumberOfSteps)
{
	u8 i;
	for(i=0 ; i<Copy_u8NumberOfSteps ; i++)
	{
		HSTEPPER_VidFullStepRight();
	}
}


void HSTEPPER_VidFullStep_StartLeft(u8 Copy_u8NumberOfSteps)
{
	u8 i;
	for(i=0 ; i<Copy_u8NumberOfSteps ; i++)
	{
		HSTEPPER_VidFullStepLeft();
	}
}


void HSTEPPER_VidHalfStep_StartRight(u8 Copy_u8NumberOfSteps)
{
	u8 i;
	for(i=0 ; i<Copy_u8NumberOfSteps ; i++)
	{
		HSTEPPER_VidHalfStepRight();
	}
}


void HSTEPPER_VidHalfStep_StartLeft(u8 Copy_u8NumberOfSteps)
{
	u8 i;
	for(i=0 ; i<Copy_u8NumberOfSteps ; i++)
	{
		HSTEPPER_VidHalfStepLeft();
	}
}


void HSTEPPER_VidStop(void)
{
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_1,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_2,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_3,LOW);
	MDIO_ERROR_STATE_t_SetPinValue(STEPPER_MOTOR_PIN_4,LOW);
}

